### ISSUE TITLE
Eyes not following mouse pointer on hover

### ISSUE THREAD

**Issue by ravin972** [Ravin972/ProximityHoverEffect#1]
### When I hover my mouse over the image of Morty, the eyes do not follow the mouse pointer. I am using Google Chrome version 98.0.4758.102. There are no error messages. Here are the steps to reproduce the issue:

1.Open the proximity.html file in a web browser.
2.Hover the mouse over the image of Morty.
3.Observe that the eyes do not follow the mouse pointer.

Labels:Bug & good first issue

**Comment by Nik42KIS** [comment]
do you have cursor:pointer in CSS?

**Comment by ravin972** [comment]
I don't have cursor:pointer in my CSS file. Could you please provide more context or clarify your question?

**Comment by Nik42KIS** [comment]
Try setting cursor:pointer in CSS for the image. Example: img{cursor:pointer}. If I understood correctly what you want, it should help.

**Comment by ravin972** [comment]
Now, it's working, great job by you.
thanks man!

**Comment by ravin972** [comment]
Bro can you add this repo with tic tac toe repo.
I want to add these file into tic tac toe repo,
Like when i play image eye follow the cursor in the game 
Can you do this?

**Comment by Nik42KIS** [comment]
Feel free to ask, I'll always be glad to help.

**Comment by Nik42KIS** [comment]
Let's follow each other.

**Comment by ravin972** [comment]
https://github.com/Ravin972/ProximityHoverEffect/issues/1#issuecomment-1501183178
can you do this?

**Comment by Nik42KIS** [comment]
try this: 
To integrate the code from the ProximityHoverEffect repository with your Tic Tac Toe project, follow these steps:

Clone the ProximityHoverEffect repository to your computer.

Locate the files responsible for the eye movement. In this case, these are the index.html, main.css, and main.js files. Copy these files to a folder in your Tic Tac Toe project, for example, a folder called eyes.

Edit the main.js file from the eyes folder. Change the code to make the eyes follow the mouse cursor instead of following elements on the page. To do this, replace the contents of the run() function with the following code:
function run() {
  const eyes = document.querySelectorAll('.eye');

  document.addEventListener('mousemove', function(event) {
    let x = event.clientX * 100 / window.innerWidth + "%";
    let y = event.clientY * 100 / window.innerHeight + "%";

    for (let i = 0; i < 2; i++) {
      eyes[i].style.left = x;
      eyes[i].style.top = y;
      eyes[i].style.transform = "translate(-" + x + ",-" + y + ")";
    }
  });
}
In your Tic Tac Toe project, where you launch the game, add a link to the main.js file from the eyes folder. To do this, add the following code to the <head> tag of the page that launches the game:
<head>
  <link rel="stylesheet" href="path/to/eyes/main.css">
  <script src="path/to/eyes/main.js"></script>
</head>
Where path/to/eyes/ is the path to the eyes folder you created in your project.

Call the run() function from the main.js file in the eyes folder after the Tic Tac Toe game page is loaded. To do this, add the following code to the <body> tag of the page that launches the game:
<body onload="run()">
  
</body>
After completing these steps, the eyes in the Tic Tac Toe game will follow the mouse cursor. Note that you can customize the eye placement in the main.css file in the eyes folder.

**Comment by ravin972** [comment]
Thanks for sharing, i'll do.👍
